### ISSUE TITLE
templates mismatch between NuGet and Github

### ISSUE THREAD

**Issue by cancodewell** [MattHoneycutt/SpecsFor#104]
I have just installed SpecsFor via NuGet. Within the packages folder (packages\SpecsFor.5.0.1\Templates\Resharper Templates), I can find some xml template files:
Attributes-File Templates.xml
Attributes-Live Templates.xml
Inheritance-File Templates.xml
Inheritance-Live Templates.xml

Here on GitHub, there are some DotSettings files.

Why is there a mismatch?

**Comment by MattHoneycutt** [comment]
Thanks for bringing that to my attention!  I switched to using an actual Resharper add-in for SpecsFor templates some time ago, and obviously forgot to update the package.  You can grab the add-in from the gallery: https://resharper-plugins.jetbrains.com/packages/SpecsFor.Templates.R90/

**Comment by MattHoneycutt** [comment]
These have been removed from the latest prerelease package.
