### ISSUE TITLE
Attribute-based Given contexts not supported?

### ISSUE THREAD

**Issue by cancodewell** [MattHoneycutt/SpecsFor#105]
On http://specsfor.com/examples.cshtml, there is a sample using the "Given" attribute and a parameterized constructor of the SpecsFor<T> base class. However, both do not exist in SpecsFor, neither in the source code here on Github nor the SpecsFor package that I have installed from NuGet.

On the other hand, after installing from NuGet, I have found ReSharper templates (in packages\SpecsFor.5.0.1\Templates\Resharper) that rely on using the "Given" attribute and a parameterized constructor of the SpecsFor<T> base class, these templates are:
Attributes-File Templates.xml
Attributes-Live Templates.xml

Thus, code generated by these templates can´t be compiled.

**Comment by MattHoneycutt** [comment]
Ugh, I need to update those examples!   The parameterized-Given attribute was removed some time ago.  Thanks for bringing that to my attention!

**Comment by cancodewell** [comment]
Ok, thank you for the quick response!

**Comment by MattHoneycutt** [comment]
Finally fixed the example.  It should be live on the website shortly.
