### ISSUE TITLE
Prevent AutoMocker configuration

### ISSUE THREAD

**Issue by tboby** [MattHoneycutt/SpecsFor#107]
My SUT is a class without a public constructor. I'd like to be able to override the AutoMocker and provide my own instance of the SUT. 
E.g.

```
 public class Foo
    {
        public int Bar { get; }
        private Foo(int bar)
        {
            Bar = bar;
        }
        public static Foo CreateFoo()
        {
            return new Foo(5);
        }
    }

 public class FooSpecs
    {
        public class when_a_foo_is_created : SpecsFor<Foo>
        {
            protected override void ConfigureContainer(IContainer container)
            {
                container.Configure(cfg => cfg.For<Foo>().Use(Foo.CreateFoo()));
            }

            [Test]
            public void then_bar_is_set_correctly()
            {
                SUT.Bar.ShouldEqual(5);
            }
        }

    }
```

Unfortunately this fails with:

```
Parameter name: Project.UnitTests.Foo must have at least one public constructor to be plugged in by StructureMap
   at StructureMap.Pipeline.ConstructorInstance`1..ctor(Type concreteType)
   at StructureMap.Pipeline.SmartInstance`2..ctor(Expression`1 constructorSelection)
   at StructureMap.Configuration.DSL.Expressions.CreatePluginFamilyExpression`1.Use[TConcreteType]()
   at StructureMap.AutoMocking.AutoMocker`1.<>c.<.ctor>b__1_0(ConfigurationExpression x)
   at StructureMap.PipelineGraph.Configure(Action`1 configure)
   at StructureMap.Container.Configure(Action`1 configure)
   at StructureMap.AutoMocking.AutoMocker`1..ctor(ServiceLocator serviceLocator)
   at SpecsFor.AutoMocking.MoqAutoMocker`1..ctor()
   at SpecsFor.SpecsForEngine`1.Init()
```

This seems to be because Structuremap.AutoMocker tries to create the configuration for the SUT type as soon as you create `MoqAutoMocker`. As far as I can tell all the hooks into the base SpecsFor class are too late. The only workaround I can find is to use `SpecsFor<Object>`, and then set up the SUT myself.

Am I just trying to use SpecsFor in a way it isn't supposed to be used? My example is a bit flawed, but it's more that I can't easily opt-out of the automocker and set up SUT myself if the SUT is a concrete type with no public constructor.

**Comment by adamswallows** [comment]
You should be able to override "InitializeClassUnderTest" to setup the SUT.

**Comment by tboby** [comment]
The exception happens before InitializeClassUnderTest is called.
https://github.com/MattHoneycutt/SpecsFor/blob/2a4d0899df8815459d449fca4193a91515870cd0/SpecsFor/SpecsForEngine.cs#L43-L49

Yes, you're right, I can work around this by using `SpecsFor<Object>` and `InitializeClassUnderTest` but that doesn't prevent the exception with `SpecsFor<Foo>`.

**Comment by MattHoneycutt** [comment]
Hi @tboby,

You *might* (I haven't tried it) be able to fix it by overriding the mocking container's configuration for Foo.  Here's more info about how StructureMap selects constructors: http://structuremap.github.io/registration/constructor-selection/

The code might look roughly like this:

```
container.Configure(x => 
{
    x.For<Foo>().ConstructUsing(() => Foo.CreateFoo());
});
```

Again, I'm *not* sure that will work.  If not, then your best best is probably to drop back to using SpecsFor<object> and handling Foo's construction yourself.
