### ISSUE TITLE
Controller which is part of an area does not have route rendered correctly.

### ISSUE THREAD

**Issue by JohnEffo** [MattHoneycutt/SpecsFor#11]
I have the following configuration:

```
Console.WriteLine("Creating config");
var config = new SpecsForMvcConfig();

 ////SpecsFor.Mvc can spin up an instance of IIS Express to host your app 
 ////while the specs are executing.
 Console.WriteLine("Registering IIS Express");
 config.UseIISExpress()
 //To do that, it needs to know the name of the project to test...
 .With(Project.Named("AppointmentReminder"))
  //And optionally, it can apply Web.config transformations if you want 
  //it to.
  .ApplyWebConfigTransformForConfig("IntergrationTests");



  Console.WriteLine("Registering Areas");
  config.RegisterArea<CustomerAreaRegistration>();
  config.RegisterArea<SettingsAreaRegistration>();

  //In order to leverage the strongly-typed helpers in SpecsFor.Mvc,
   //you need to tell it about your routes.  Here we are just calling
  //the infrastructure class from our MVC app that builds the RouteTable.
  Console.WriteLine("Registering Routes");
  config.BuildRoutesUsing(r => RouteConfig.RegisterRoutes(r));

  ///Setup intergration Db
  Console.WriteLine("Setting up db");
  config.Use<SetUpDatabase>();

  //SpecsFor.Mvc can use either Internet Explorer or Firefox.  Support
  //for Chrome is planned for a future release.
  Console.WriteLine("Setting up browser driver");
  config.UseBrowser(BrowserDriver.InternetExplorer);

  //The host takes our configuration and performs all the magic.  We
  //need to keep a reference to it so we can shut it down after all
  //the specifications have executed.
   Console.WriteLine("Starting host");
   _host = new SpecsForIntegrationHost(config);
   _host.Start();
```

And the following Area registrations

```
 namespace MyApp
 {
  public class CustomerAreaRegistration : AreaRegistration
  {
    public override string AreaName
    {
        get
        {
            return "Customer";
        }
    }

    public override void RegisterArea(AreaRegistrationContext context)
    {
        context.MapRoute(
            "Customer_default",
            "Customer/{controller}/{action}/{id}",
            new { area = "Customer", action = "defaultAction", id = UrlParameter.Optional            ,
            new string[] { "MyApp.Areas.Customer.Controllers" } 

           );
       }
   }
}

namespace MyApp
{
 public class SettingsAreaRegistration : AreaRegistration
 {
     public override string AreaName
     {
         get
         {
             return "Settings";
         }
     }

     public override void RegisterArea(AreaRegistrationContext context)
     {
         context.MapRoute(
             "Settings_default",
            "Settings/{controller}/{action}/{id}",
            new { action = "Index", id = UrlParameter.Optional }
         );
     }
 }
```

}

The controller Register is in the Customer Area so:

```
//arrange
var app = new MvcWebApp();
app.NavigateTo<RegisterController>(controller => controller.CustomerDetails());
```

Should map to \Customer\Register but it maps to \Register. I looked at the NavigateTo method and it uses 
    var url = helper.BuildUrlFromExpression(action);
 to generate the route.

So in my app a wrote the extension method.

```
public static string GetRoute(this HtmlHelper value)
    {
        return value.BuildUrlFromExpression<RegisterController>(c => c.CustomerDetails());
    }
```

to check if the fakes you were using were causing any problems, it renders the route as:

/Register

So either my area configuration mapping is missing something or the BuildUrlFromExpression which you are using to generate URLs, does not honor areas, which is causing SpecsFor.Mvc to not map routes correctly. 

The versions I am using are:

   package id="SpecsFor" version="3.0.0" targetFramework="net45" 
   package id="SpecsFor.Mvc" version="2.2.0" targetFramework="net45"

Incidentally I have the a couple of assembly redirects in my app.config, which i copied from my web.config, otherwise when I try to use NavigateTo it complains that the type of my controller does not map the constraint for TController, as I am using MVC 4 on .net 4.5. I have also tried calling RegisterArea before and after BuildRoutesUsing .

Cheers
John

**Comment by MelGrubb** [comment]
I have this working using the RouteArea attribute, and the browser is going to the right area now, but calls to SUT.Route.ShouldMapTo are still throwing and failing the tests. The errors say something similar to "Expected [ControllerName] but was [AreaName]".

**Comment by MattHoneycutt** [comment]
I've been trying to reproduce this, but so far I haven't been able to.
Could you submit a small repro case?

**Comment by MelGrubb** [comment]
I have it working now. I was missing an explicit call to config.RegisterArea in my MvcAppConfig, thinking that part was automatic. I saw a comment about it in the thread that resulted in the scanning for RouteArea attributes. With the call to RegisterArea, everything is now working.

The magic combination for me seems to be:
Adding a boolean parameter to RouteConfig.RegisterRoutes to skip calling MapMvcAttributeRoutes when called from MvcAppConfig.
Explicitly calling BuildRoutesUsingAttributeRoutingFromAssemblyContaining from MvcAppConfig.
Explicitly calling RegisterArea from MvcAppConfig.

**Comment by MelGrubb** [comment]
Sorry, I misspoke with an earlier comment (now deleted), I lost my place and thought I was responding to a different issue. I'll try to work up a repro if I can. I imagine it's something I've missed or forgotten to do that you haven't. If you already have a test case that's using ShouldMapTo to test against a controller in an area, I could just look at that and see what I'm missing. Is there an example in the source already?

**Comment by MattHoneycutt** [comment]
Yeah, here's an example:
https://github.com/MattHoneycutt/SpecsFor/blob/master/SpecsFor.Mvc.Demo.AcceptanceTests/RouteTestingSpecs.cs

The controller being used in that spec has the RouteArea attribute.
