### ISSUE TITLE
SpecsFor.Mvc release tag

### ISSUE THREAD

**Issue by tboby** [MattHoneycutt/SpecsFor#121]
Hi, just read the announcement on the retirement of SpecsFor.Mvc. It's very sad to see it go; because of our industry we're not going to be migrating to ASP.NET Core for years yet. But SpecsFor.Mvc has been stable for years and will continue to be, so I'm still going to recommend it to people!

Would you mind putting a tag or branch on the latest version of SpecsFor.Mvc? If I point someone at this repository, it would be good for them to be able to find the latest source and demos.

**Comment by MattHoneycutt** [comment]
Great idea!  But instead, I went ahead and created a branch:

https://github.com/MattHoneycutt/SpecsFor/tree/dotnetframework

I actually intended do that all along, I just forgot to push the branch up.

I'm glad to hear it's still working great for you guys.  Happy coding!
