### ISSUE TITLE
Support for .net standard 2.1

### ISSUE THREAD

**Issue by seanrockster** [MattHoneycutt/SpecsFor#123]
Hi Matt

I hope you're well and safe.

Do you have any plans to upgrade to support .net standard 2.1? I'm guessing structuremap is the challenge as its been sunsetted and doesn't support 2.1?

Kind Regards
Sean

**Comment by MattHoneycutt** [comment]
Hi Sean!

Yeah, at some point, I'm going to have to release a version that doesn't use StructureMap at all.   

For now, I'm actually using SpecsFor on a couple of .NET Core 3 projects without issue.  The assembly you are testing can target netstandard2.1, and the spec project can target netcoreapp3.1.  That *should* work, but if not, let me know!

**Comment by seanrockster** [comment]
Hi Matt.

The projects are all .net core 3.1 because of other dependencies. Yes, a version without a dependency on a specific container would be great. I forked the repo but I've not had any time to look into it.
