### ISSUE TITLE
Getting "Unable to find solution file, traversed up to 'C:\'" error on build server

### ISSUE THREAD

**Issue by MelGrubb** [MattHoneycutt/SpecsFor#35]
I have a test suite that is more or less working on my local machine, following the examples on this project and the SpecsFor.MVC site. I'm having trouble getting it to work on the TFS build server, though. It would appear that the tests are failing during setup, when SpecsFor.MVC tries to use the Project.Named method to find the web project.

Here is the complete error message:
SetUp : System.InvalidOperationException : Unable to find solution file, traversed up to 'C:\'.  Your test runner may be using shadow-copy to create a clone of your working directory.  The Project.Named method does not currently support this behavior.  You must manually specify the path to the project to be tested instead.

I get what the message is saying, but haven't found a good solution to the problem yet. If one is known, for instance TFS build settings that would stop it from using a shadow copy of the site in some Guid-named temporary folder, then it would be nice if that were added to the examples, or a faq of some kind.

**Comment by stevozilik** [comment]
A better discovery code, that searches 'around', rather than just 'up'. Our build machine build structure has code and dlls in folders next to each other

```javascript
public static string DiscoverProject(string projectName, string currentFolder = null)
        {
            currentFolder = currentFolder ?? Environment.CurrentDirectory;

            Debug.WriteLine(String.Format("Discovering path to project {0} for Specs4MVC tests. Starting in {1}", projectName, currentFolder));

            string projectPath = null;

            var directoryInfo = new DirectoryInfo(currentFolder);

            while (projectPath == null)
            {
                var solutionFiles = directoryInfo.GetFiles("*.sln", SearchOption.AllDirectories);
               
                foreach (var solutionFile in solutionFiles)
                {
                    Debug.WriteLine(String.Format("Found a possible solution file {0}", solutionFile.FullName));

                    projectPath = Path.Combine(solutionFile.Directory.FullName, projectName);

                    if (Directory.Exists(projectPath))
                    {
                        Debug.WriteLine(String.Format("Found suitable project path {0}", projectPath));
                        break;
                    }
                    else
                    {
                        Debug.WriteLine(String.Format("Assumend project path {0} does not exist. Continuing search...", projectPath));
                        projectPath = null;
                    }
                }

                if (projectPath == null)
                {
                    if (directoryInfo.Parent == null)
                    {
                        string message = String.Format("Unable to find project file {0}. Started at {1}, Search all the way up to {2}",
                           projectName,
                           currentFolder,
                           directoryInfo.FullName);
                        throw new InvalidOperationException(message);
                    }
                    else
                    {
                        directoryInfo = directoryInfo.Parent;
                    }
                }
            }

            return projectPath;
        }
```

**Comment by MattHoneycutt** [comment]
Nice.  I'll have to experiment with it to make sure it still honors the typical project setup first (solution in the parent folder), but I can probably incorporate this into the project.

**Comment by stevozilik** [comment]
Cool.

It does go 'up', same way as yours, but it also looks 'down' as it goes up. Furthermore it check if the project folder actually exits, to avoid picking up incorrect solution/project. It works fine in both dev and build configurations for us.

**Comment by MattHoneycutt** [comment]
It took me long enough, but I finally merged your DiscoverProject approach in to SpecsFor.Mvc.  It'l be in the release later today.  Thanks!
