### ISSUE TITLE
SpecsFor.MVC radio buttons

### ISSUE THREAD

**Issue by neuhoffm** [MattHoneycutt/SpecsFor#49]
Is there a way to select a radio button field? I'm not seeing one, thinking that something like this http://stackoverflow.com/a/26191022/1062633 could be an option, but wasn't sure how that fits into the overall vision of the field validation. The main issue I see is that the FluentField assumes a single field for each model property.

**Comment by MattHoneycutt** [comment]
Ya know, you're right, this is a case I haven't handled in the core of SpecsFor.Mvc.  I remember needing to support radio buttons on a project a while back, but I don't think the extension method I wrote there ever found its way back in to SpecsFor.Mvc.  

I'll put this on the radar to tackle soon, but in the meantime, pull-requests are welcome! :)

**Comment by MattHoneycutt** [comment]
I believe this has been addressed now!
