### ISSUE TITLE
Issue parsing email address with plus symbol

### ISSUE THREAD

**Issue by markmni** [MattHoneycutt/SpecsFor#51]
If an email is sent to an address like test+1@user.com the resulting address in the To field of the MailMessageEx will end up as 1@user.com.

I've created a fork which passes the addressList string directly to the Add method of the MailItemCollection, instead of splitting with the regex and calling Add with the individual addresses, and an extra test with an example of one of the previously problematic email addresses. I can send a PR if that sounds like something you'd like to integrate? Thanks!

**Comment by MattHoneycutt** [comment]
Definitely!  Please send the pull request on over, and I'll get it merged
in.  Thanks!

**Comment by MattHoneycutt** [comment]
Fixed!
