### ISSUE TITLE
Add ability to set drivers in BrowserDriver

### ISSUE THREAD

**Issue by nfpowe01** [MattHoneycutt/SpecsFor#53]
It would be super helpful if we were able to set our own versions of a driver inside of BrowserDriver within SpecsFor.MVC.  I'd like to be able to set my own browser capabilities and point it to a driver location and I can't do that right now.

**Comment by MattHoneycutt** [comment]
Can you give me a bit more info on what you'd like to do?  Pseudo-code or
the like would be great.  I want to make sure I understand the request
before I start thinking up how to implement it.

**Comment by nfpowe01** [comment]
Lol, I can do you one better, I went ahead and implemented it in my cloned version.  All I had to change was to remove the readonly from the three BrowserDrivers in the BrowserDriver class and then make the BrowserDriver constructor that takes in a browserFactory public.  This allowed me to use my own implementation of a browser factory to easily change the driver itself as I have below:
```C#
BrowserDriver.InternetExplorer = new BrowserDriver(() =>
{
	InternetExplorerOptions options = new InternetExplorerOptions { IntroduceInstabilityByIgnoringProtectedModeSettings = true };

	return new InternetExplorerDriver(_testSettings.BrowserDriverLocation, options);
});

BrowserDriver.Chrome = new BrowserDriver(() =>
{
	ChromeOptions options = new ChromeOptions();
	options.AddArguments("test-type");

	return new ChromeDriver(_testSettings.BrowserDriverLocation, options);
});

BrowserDriver.Firefox = new BrowserDriver(() =>
{
	FirefoxProfile profile = new FirefoxProfile()
	{
		AcceptUntrustedCertificates = true
	};

	return new FirefoxDriver(profile);
});
```

**Comment by MattHoneycutt** [comment]
Ah, I see.  Let me mull it over for a bit.  I actually have been wanting to
revisit the BrowserDriver construct for a while, so maybe now is the time
to take a fresh look at it with your suggestions in mind...

**Comment by MattHoneycutt** [comment]
The constructor is public with the latest release.  I'll also make the static fields writeable in an upcoming release.

**Comment by MattHoneycutt** [comment]
Done, you can now overwrite the static fields with your own browser drivers.
