### ISSUE TITLE
Allow overriding of both temporary folder names when publishing to IIS Express

### ISSUE THREAD

**Issue by garybond** [MattHoneycutt/SpecsFor#62]
I ran into a problem recently where the action of publishing the target web project failed, due to an MSBuild target not being able to generate a resource file in the SpecsForMvc.TempIntermediateDir path. It turned out, after much head-scratching, that the generated file path was over the Windows MAX_PATH value of 260 characters.  In an effort to reduce the length of the file path, I thought I could shorten the path by using .WithTemporaryDirectoryName("ShortDir").

When this didn't work, and after more head-scratching, I realised that "WithTemporaryDirectoryName" rather ambiguously allows you to renamename the publish folder, not the temp folder.
The actual foldername I was attempting to shorten (SpecsForMvc.TempIntermediateDir) had no override.

It would be great if both folder names worked off the value the developer sets.

**Comment by MattHoneycutt** [comment]
Yup, I agree, that should be handled better by SpecsFor.Mvc.  I'll tackle
this in an upcoming release.

**Comment by garybond** [comment]
Thanks Matt. 
I've implemented a workaround, by renaming our build-server remote agent, shortening the path.  
As our chosen naming convention for this project was Bond girls, NatalyaSimonova has been ditched in favour of ChewMee ;-)

**Comment by MattHoneycutt** [comment]
I've marked WithTemporaryDirectoryName as obsolete, and added two new methods: WithPublishDirectory will override the build's publish directory, and WithIntermdiateDirectory will override the build's publish directory.   This change will be in today's release.
