### ISSUE TITLE
Using Windows Authentication with SpecsFor.Mvc should be (much) easier.

### ISSUE THREAD

**Issue by MattHoneycutt** [MattHoneycutt/SpecsFor#63]
Right now, using Windows Auth requires a custom applicationHost.config file for IIS Express.  It'd rather it be as simple as this:

```
        var config = new SpecsForMvcConfig();
        config.UseIISExpress()
            //.ApplicationHostConfigurationFile(@"applicationhost.config")
            .UseWindowsAuthentication()
            .With(Project.Named("WindowsAuthSampleApp"));
```

**Comment by Rajiv-Kulkarni** [comment]
I don't see that option- running in VS2015, targeting .net 4.6.1.

**Comment by MattHoneycutt** [comment]
This issue is a request to implement the UseWindowsAuthentication() option.  It has not been implemented yet.  You can use the ApplicationHostConfigurationFile option for now, but you have to provide your own config file that is set up for Windows auth.

**Comment by MattHoneycutt** [comment]
No plans to implement right now.
