### ISSUE TITLE
Specsfor.mvc, how can test view has upload input

### ISSUE THREAD

**Issue by jackyphuong** [MattHoneycutt/SpecsFor#64]
Hi,

I am using aps.net mvc 5 and run test on view has upload file control. It seems this feature has not still be implemented, is it right? Do u any plan to support it?

Thanks,

Jacky

**Comment by MattHoneycutt** [comment]
I don't have any plans to implement it right now.  Pull requests are accepted though! :)

**Comment by jackyphuong** [comment]
tks :) will wait for new release
