### ISSUE TITLE
Testing a site with RequireHttpsAttribute

### ISSUE THREAD

**Issue by neuhoffm** [MattHoneycutt/SpecsFor#66]
Just wondering if there's a way to signal specsfor to spin up a https site instead of an http one. Currently it goes to https://localhost which seems to be relying on regular IIS instead of IIS express so that doesn't exist.

Filter.config
```
    public static void RegisterGlobalFilters(GlobalFilterCollection filters)
    {
        filters.Add(new HandleErrorAttribute());
        filters.Add(new RequireHttpsAttribute());
    }
```

Setup Method
```
            var config = new SpecsForMvcConfig();

            config.UseIISExpress()
                .With(Project.Named(@"folder"), @"solution")
                .UseMSBuildExecutableAt(@"C:\program files (x86)\msbuild\12.0\bin\msbuild.exe")
                .CleanupPublishedFiles()
                .ApplyWebConfigTransformForConfig("Debug");

            config.RegisterArea<ApplicationAreaRegistration>();
            config.RegisterArea<AdminAreaRegistration>();
            config.BuildRoutesUsing(r => RouteConfig.RegisterRoutes(r));
            config.UseConventions<BootstrapConventions>();
            config.UseBrowser(BrowserDriver.Chrome);

            this.integrationHost = new SpecsForIntegrationHost(config);
            this.integrationHost.Start();
```

**Comment by MattHoneycutt** [comment]
Is there something in the web project that is redirecting non-SSL traffic?
With the config you've got, it will use IIS Express, but if your web app is
then trying to redirect to an SSL address, things won't work because IIS
Express isn't configured for it.

I'd be interested in adding support for SSL, but I'm not sure what it would
look like exactly.  Should it configure an instance of IIS Express that
only listens for HTTPS traffic?  Or should it spin up two end-points?

As an interim solution, you *could* do it by creating your own
applicationHost.config file that includes HTTP and HTTPS bindings, then
telling SpecsFor.Mvc to use that host file instead of the default one.

**Comment by neuhoffm** [comment]
Yep, the [requirehttpsattribute](https://msdn.microsoft.com/en-us/library/system.web.mvc.requirehttpsattribute%28v=vs.118%29.aspx) filter redirects all traffic to https. 
My initial thought would be that it mirrors the iis express implementation of a web project where you can set ssl enabled to true at which point it would start up a https site otherwise, it would start up an http. The scenario where both a http and https site could be necessary would most likely be limited to when somebody writes their own https redirect logic and wants to test it.

**Comment by MattHoneycutt** [comment]
Sounds good to me.  I'll keep this on the backlog for the next time I'm
adding new features.  Until then, pull requests are welcome! :) :)

**Comment by neuhoffm** [comment]
I'd be happy to do a PR but would have no idea where to start. Any pointer
you can give and I'll get started!

**Comment by MattHoneycutt** [comment]
Off the top of my head, I *think* this will require emitting a custom
applicationHost.config file, then instructing IISExpress.exe to use that
instead.  It won't be easy.  The config file will need to include an entry
for https binding against the target port.

Long-term, I actually think emitting a custom applicationHost.config file
should be the standard behavior of SpecsFor.Mvc.  The pure command-line
approach it currently uses is very limited.  There are a ton of things you
can tweak in IISExpress, but most are not exposed as command-line
parameters.  You have to use a config file.
