### ISSUE TITLE
Check entitystate

### ISSUE THREAD

**Issue by Jogai** [MattHoneycutt/SpecsFor#69]
I have a test database with some data. My unit tests act upon this data but don't persist changes. EntityFramework savechanges isn't called, I plan on doing that in my integration tests. That way I don't have to mock ef, and I test the real interaction in combination with mysql (mysql.data.entity has bugs which aren't detected with a mocked ef instance).

I want to check for entity state. How can I do this?

Here is a simplified approach explaining my problem. Tree object has one Twig, a twig can have one Bird, but a bird can have more than one Twig.

```c#
        public class When_a_user_rejects : SpecsFor<Logic>
        {
            private readonly ApplicationDbContext _db = new ApplicationDbContext();
            private Tree _result = new Tree();

            protected override void InitializeClassUnderTest()
            {
                SUT = new Logic(_db);
            }

            protected override void When()
            {
                _result = SUT.Reject(4, 1);
            }

            [Test]
            public void Then_Tree_is_changed()
            {
                _db.Entry(_result).State.ShouldEqual(EntityState.Modified); //Test passes
            }

            [Test]
            public void Then_Tree_is_not_approved()
            {
                _result.Approved.ShouldBeFalse(); //Test passes
            }

            [Test]
            public void Then_Twig_is_deleted()
            {
                _result.Twig.ShouldBeNull(); //Test passes, altough I would like to check here for Entity state
            }

            [Test]
            public void Then_Bird_is_not_deleted()
            {
                _db.Entry(_result.Twig.Bird).State.ShouldEqual(EntityState.Unchanged); //Test fails because Tree is null
            }
        }
```

The method I'm testing here looks like this:

```c#
        public Tree Reject(int id, int userId)
        {
			Tree tree = _db.Forest.Where(tree => tree.Id == id).Include(tree => tree.Twig).Include(tree => tree.Twig.Bird);            
            tree.Approved = false;
			if(BirdIsSittingOnMoreTwigs(tree.Twig.Bird)))
			{
				_db.Entry(tree.Twig.Bird).State = EntityState.Unchanged;
			}
			else
			{
				_db.Entry(tree.Twig.Bird).State = EntityState.Deleted;
			}
			_db.Entry(tree.Twig).State = EntityState.Deleted;
            return tree;
        }
```

I cant query the birds again, because savechanges isn't called. The bird will always exist, and a new query always marks it unchanged.

**Comment by MattHoneycutt** [comment]
Thanks for the detailed example.  I may have to pull down your sample and step through it myself to see exactly what's going on.  It may be difficult to achieve what you're going for here. But, when this line is called...

   _db.Entry(tree.Twig).State = EntityState.Deleted;

It is actually nulling out the Twig property, correctly?

**Comment by Jogai** [comment]
Yes, test Then_Twig_is_deleted() passes, and on debugging I see an actual null object.

**Comment by Jogai** [comment]
Yes, test Then_Twig_is_deleted() passes, and on debugging I see an actual null object.

**Comment by MattHoneycutt** [comment]
That's what I thought.  In that case, I don't think you can really write specs against your _result.Twig.Bird, because the execution of your SUT is actually destroying the reference to _result.Twig.

BUT, could you capture _result.Twig into a field before your When executes?  Then you could write your specs against that field.

As another option, you may want to consider switching to making this an actual integration spec.  It's actually quite easy to do with SpecsFor's convention system.

**Comment by Jogai** [comment]
It makes sense to do it as an integration test if we get to that. Thanks for your reaction.
