### ISSUE TITLE
SpecsFor without Should

### ISSUE THREAD

**Issue by HerrLoesch** [MattHoneycutt/SpecsFor#71]
It would be great if the Should framework wouldn't be an integral part of SpecsFor. We usually use FluentAssertions and don't need Should.

**Comment by MattHoneycutt** [comment]
Just so I understand the request, is there any issue with using FluentAssertions with SpecsFor?  I know you do pick up an unnecessary dependency on Should in your case, but are they conflicting in some way or anything like that?

**Comment by HerrLoesch** [comment]
They are not conflicting but the dependency Should adds, causes confusion in our team. When I compare the open architecture of SpecsFor, which is absolutly great, and the packaging than I don't understand why you've packed so many external dependencies into it. Moq, StructureMap and Should are all frameworks we've just added to our project because of SpecsFor. Before this, we used FakeItEasy, AutoFac and FluentAssertions. In case of StructureMap and Moq I can some how understand why you need the coupling. But from my perspective Should is a framework SpecsFor should not have any reference on because every body who want to use it, can download it on his own.

**Comment by MattHoneycutt** [comment]
I'll consider this as part of future plans to make the entire SpecsFor framework more pluggable.
