### ISSUE TITLE
Will you support ASP.NET MVC 5.2.3 ?

### ISSUE THREAD

**Issue by ffalardeau** [MattHoneycutt/SpecsFor#72]
Hello, 

I really appriciate your tool, we were able to build elegant system tests in a few hours ! 

I use ASP.NET MVC 5.2.3 and there seems to be a problem when using System.Web.Mvc 5.2.3.0 in our System tests project. So we need to live with Mvc 5.2.3.0 for the web application and 5.2.2.0 for the  system tests project. 

We are using .NET Framework 4.5.1 for all our projects. 

Thank you, 
Francis

**Comment by MattHoneycutt** [comment]
Hi Francis, are you using SpecsFor, or SpecsFor.Mvc?  Both should be able
to work with Mvc 5.2.3, but you may need to add binding redirects.  You can
use the Package Manager Console in Visual Studio to do this.  Make sure
your test project is configured as the active project, then run the
command, 'Add-BindingRedirect'.

Please let me know if that doesn't work.

**Comment by ffalardeau** [comment]
It seems like the BindingRedirect in our system tests project was limited to 5.2.2.0. 

Works perfectly, thanks for the help.
