### ISSUE TITLE
SpecsForMvc with ADO.NET

### ISSUE THREAD

**Issue by ddana0909** [MattHoneycutt/SpecsFor#73]
Does SpecsForMvc work for MVC applications where the db access is done through ADO.NET?

**Comment by MattHoneycutt** [comment]
Sure, SpecsFor doesn't care what you use for data access.  That said, there
are no built-in helpers for working with ADO.NET if you want to do
integration testing.  You'll want to write some helpers and/or conventions
to make your life easier.

**Comment by ddana0909** [comment]
How can you connect to the db? In my application, the ConnectionString is set at aplication startup form a .config file. (All methods calling procedures from the db, will use this ConnectionString to establish the connection).

**Comment by MattHoneycutt** [comment]
You can add a config file to your test project to store a test-specific
connection string.  All the major test runners support this.  As for
reading the connection string in and initializing your infrastructure, you
can create a setup fixture (
http://nunit.org/index.php?p=setupFixture&r=2.6.3).

I hope that helps!
