### ISSUE TITLE
Ability to set size of browser window

### ISSUE THREAD

**Issue by garybond** [MattHoneycutt/SpecsFor#74]
I've been trying to find a way to change the size of the browser window that pops up when the tests are under way. The only info I can find relates to Selenium and I wondered if/how I would go about setting these options from within the SpecsForMvcConfig ?

These are the Selenium options:
driver.manage().window().setSize(new Dimension(1024,768));
driver.manage.window.maximize();

Any ideas?

**Comment by MattHoneycutt** [comment]
Right now, you'll have to access Selenium directly to configure the window
size.  The MvcWebApp exposes the browser driver, so you can use that to do
this.

I do like the idea of supporting this as a SpecsForMvcConfig option
though.  I'll try to look in to it soon.  Until then, pull requests are
accepted! :D

**Comment by garybond** [comment]
Thanks Matt. I've got it working via MvcWebApp for now.

**Comment by MattHoneycutt** [comment]
This is now implemented and will ship with the new release later today.  You can specify the window size by doing:

    var config = new SpecsForMvcConfig();
    //Config calls..
    config.SetBrowserWindowSize(width: 1024, height: 768);
