### ISSUE TITLE
Not compatible with .NETPlatform v5.4

### ISSUE THREAD

**Issue by cwaymanuk** [MattHoneycutt/SpecsFor#78]
Hey

Is it in the pipeline to make SpecsFor compatible with .NETPlatform v5.4?

Kind Regards

**Comment by MattHoneycutt** [comment]
I hadn't considered it, but I'm all for the idea.  I'll try to investigate
soon.

On Tue, Jan 12, 2016 at 10:24 AM cwaymanuk <notifications@github.com> wrote:

> Hey
>
> Is it in the pipeline to make SpecsFor compatible with NETPlatform v54?
>
> Kind Regards
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MattHoneycutt/SpecsFor/issues/78>.
>
-- 
*Matt Honeycutt*
*Pluralsight Author & Senior Web Application Architect*
[image: Heroic Applications] <http://heroicapplications.com/>
pluralsight vids <http://www.pluralsight.com/author/matt-honeycutt> | blog
<http://trycatchfail.com/> | website <http://heroicapplications.com/> |
@matthoneycutt <http://twitter.com/matthoneycutt>

**Comment by MattHoneycutt** [comment]
Dropping for now.  Open to a pull request if someone would like to tackle this.
