### ISSUE TITLE
SpecsFor production change proposal

### ISSUE THREAD

**Issue by patroza** [MattHoneycutt/SpecsFor#79]
What a great tool! I especially love the full integration capabilities with VS Test Explorer + CodeLens. Something that e.g MSpec, NSpec or NUnit.Specifications seem to lack. So bravo :)

I would like to propose the following changes to the SpecsFor class,
https://gist.github.com/sickboy/aaa6d287105bd53c5915
1. Abstract versions of Given and When:
   - Abstract makes it clear that you have to implement it (what is a test without a Given and a When?). And the IDE helps with this (errors+quick code generation)
   - Abstract makes it clear that you don't need to call base.X()
2. A fluent implementation of Given<X>, that can be chained with .And<Y>()'s I find this especially helpful when using C# 6.0's expression bodies:

```
            protected override void Given() =>
                Given<TheCarIsNotRunning>()
                    .And<TheCarIsParked>();
```

3 Sealed TearDown. since AfterSpec seems to be the method to override when wanting to perform our own TearDown behavior. Overriding TearDown would allow to override internal behavior of SpecsFor suite, not something I believe would be commonly used.

I think some of the design choices of the class were made to be able to test the class (better), however such choices are IMO harmful when using it in production. Perhaps therefore there should be a SpecsForInternal<T> that can be used for testing, and SpecsFor<T> that looks a bit like my suggested class?

**Comment by MattHoneycutt** [comment]
Thanks for the ideas! 

I definitely like number 3.  I actually consider making that change every time I stumble across that code.  I don't remember why I made it virtual to begin with, but at this point, I don't think there's any reason for it to remain so.

As for number 1, I actually do find it fairly common to make specs with just a When and no Given.  I have, however, considered making When abstract and requiring it to be implemented.  I'm definitely open to the idea.  

I'm not sure how I feel about number 2.  I don't make heavy use of context classes myself anymore.  Instead, I usually go with the convention system.  I'd be interested to see how many people do use context classes though.  If there's sufficient interest in it, I'd be fine with merging a pull request to add this fluent functionality.

**Comment by sickboy** [comment]
Thanks for the response!

What is the convention system exactly? The documentation is incomplete on this subject. (Also the "Given" attribute as per the README.MD examples, is nowhere to be found)

**Comment by MattHoneycutt** [comment]
Hi @sickboy, I apologize for taking so long to get back to you.  I realized I forgot to write the docs for the convention system, so I spent the past couple of weeks putting something together: https://specsfor.readme.io/docs/overview

I hope that helps!

**Comment by MattHoneycutt** [comment]
Geeze, it's embarrassing how long this issue has sat open...

I've actually started to implement number 3 in the latest preview release.  The TearDown method is marked as Obsolete, so anyone overriding it should have time to switch to overriding AfterSpec instead.  I'll actually nuke this method in the following major release. 

As for number 2, I like the syntax, but probably won't be getting to that for a while.  If anyone wants to send in a pull request for that, I'd be happy to take a look.
