### ISSUE TITLE
ShouldLookLike incorrectly passes on arrays with differing numbers of elements

### ISSUE THREAD

**Issue by MattHoneycutt** [MattHoneycutt/SpecsFor#82]
Doing actual.ShouldLookLike(() => new[] { /\* some element */}) will pass even if actual contains more than a single element.  It should fail.

**Comment by derekgreer** [comment]
This should be fixed with the latest version of ExpectedObjects.

**Comment by derekgreer** [comment]
I'm pursing the code at https://github.com/MattHoneycutt/SpecsFor/blob/master/SpecsFor/ShouldExtensions/ShouldLooksLikeExtensions.cs, but don't see any actual use of ExpectedObjects so perhaps you've got your own comparison stuff going on.  My apologies for any confusion.

If you are still using ExpectedObjects, there's been some updates you might take advantage of.

**Comment by MattHoneycutt** [comment]
I do still use ExpectedObjects in some places, but I *think* this particular issue is unrelated.
