### ISSUE TITLE
Out of Box - SpecsFor.Helpers.Web references wrong MVC version

### ISSUE THREAD

**Issue by rswetnam** [MattHoneycutt/SpecsFor#84]
I forked and tried to run SpecsFor.  SpecsFor.Helpers.Web will not build because the version System.MVC that it expects - 5.2.3.0 is higher than the referenced assembly  5.2.0.0.

What to do?   I think identifying and fixing this sort of annoying installation? bug be a high priority for a tool whose aim is to make life simpler for folks that try it to remove complexity.

**Comment by MattHoneycutt** [comment]
So you checked out the solution, but were unable to build the SpecsFor.sln solution, right?  I just rebuilt it a second ago, so I'm not sure what's wrong.  Did you make any changes to the solution? 

The projects having different dependencies won't prevent them from building, nor will it prevent projects from using them, as long as you have *at least* version 5.2.0.0 of System.Web.Mvc.  You might see warnings during the build, but that's all.

**Comment by rswetnam** [comment]
Thanks Matt - I will build a create a new solution and create a proper
github sample as you suggested in your previous post.  I guess where I got
confused besides being weak in Github is that I thought I saw a major
version change in Moq which I just assumed would contain breaking changes
and... managed to work my way deep into a rabbit hole.  Thanks for your
patience.  I will restart tomorrow, with a clearer mind, hopefully...

Roger

On Thu, Feb 18, 2016 at 2:48 PM, Matt Honeycutt <notifications@github.com>
wrote:

> So you checked out the solution, but were unable to build the SpecsFor.sln
> solution, right? I just rebuilt it a second ago, so I'm not sure what's
> wrong. Did you make any changes to the solution?
>
> The projects having different dependencies won't prevent them from
> building, nor will it prevent projects from using them, as long as you have *at
> least* version 5.2.0.0 of System.Web.Mvc. You might see warnings during
> the build, but that's all.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MattHoneycutt/SpecsFor/issues/84#issuecomment-185966608>
> .
>



-- 
Roger Swetnam
p.  604-408-5703
c.  778-848-3118

**Comment by MattHoneycutt** [comment]
Everything in the solution now uses MVC 5.2.3.
