### ISSUE TITLE
SUT is null

### ISSUE THREAD

**Issue by RedX2501** [MattHoneycutt/SpecsFor#86]
I have installed the latest version (4.7.1) from nuget and after quite some fiddling with the dependencies (why does not depend on SpecsFor if all the tutorials use it?) I was able to build.

My Main application is targeted at .Net 4.5.0 whereas the project for testing targets .Net 4.5.1 because that's the version SpecsFor is compiled against.

After mixing and matching following tutorials: http://blog.nwoolls.com/2013/05/30/integration-testing-asp-net-mvc-projects-with-specsfor-mvc/ https://specsfor.readme.io/docs/using-specsformvc-with-windows-authentication and the source from Github I finally got a test to run with MSTest (what is the support status for MSTest?).

The first tutorial in the list tells me to instantiate a MvcWebApp myself and doing that a browser window opens and it navigates to where I want to. If I try to use SUT it is null.

There are no errors, no warnings when compiling or running. It just crashes with SUT being null.

**Comment by MattHoneycutt** [comment]
I'm assuming you are talking about SpecsFor.Mvc, right?   SpecsFor.Mvc will work with MSTest, but I plan to drop support for that completely in the future, and to require the use of SpecsFor (which will probably never support MS Test unless someone wants to submit a pull request).   

So, the two tutorials you referenced are not going to be compatible.  Nate is showing how to use SpecsFor.Mvc with MS Test *without* SpecsFor.  The official docs just show how to do it *with* SpecsFor.  The steps are totally different for each (and significantly easier if you use SpecsFor).

So, which approach are you trying to take?  Are you using SpecsFor, or are you trying to use MS Test?

**Comment by RedX2501** [comment]
Sorry if I seem confused but what is the difference between SpecsFor and SpecsFor.Mvc? I could not find a authoritative source on that.

I will probably have to go with SpecsFor.Mvc because the rest of the tests use Mstest.

I'm also confused because the examples in github also seem to use SpecsFor<> in the Mvc project?

**Comment by RedX2501** [comment]
Does SpecsFor<Web> Helper work with SpecsFor.Mvc, i could not find anything on it.

**Comment by RedX2501** [comment]
I have switched over to SpecsFor.Mvc and removed the dependency to SpecsFor.

In your post http://trycatchfail.com/blog/post/Using-SpecsForMvc-Reading-Data you recommend using MvcDisplayTemplates. I tried but in conjunction with Html.ActionLink for example no Id span was generated. The project also seems to contain almost no files on github (in SharedViews folder)?

What is necessary to do to support MsTest under SpecsFor? If you are removing support for MsTest from SpecsFor.Mvc are there any chances that adding support to SpecsFor will succeed? I assume there must have been problems for you to be considering dropping support?

**Comment by MattHoneycutt** [comment]
The display templates won't affect action link generation.  They affect
things rendered using Html.DisplayFor.  For action links, you can use one
of the other built-in helpers to find and click on links in a
strongly-typed way.

As for MS Test support, I'm not necessarily dropping support for it due to
issues.  I'm going to make SpecsFor.Mvc require SpecsFor because it makes
sooooo many things easier.  Not just in terms of implementation, but in
terms of documentation and usage as well.

I doubt SpecsFor will ever work with MS Test.  I personally don't like MS
Test.  Even Microsoft has stopped using it.  I think there's a greater
chance of SpecsFor supporting xUnit than there is of SpecsFor ever
supporting MS Test.

On Fri, Feb 19, 2016 at 12:25 AM RedX2501 <notifications@github.com> wrote:

> I have switched over to SpecsFor.Mvc and removed the dependency to
> SpecsFor.
>
> In your post
> http://trycatchfail.com/blog/post/Using-SpecsForMvc-Reading-Data you
> recommend using MvcDisplayTemplates. I tried but in conjunction with
> Html.ActionLink for example no Id span was generated. The project also
> seems to contain almost no files on github (in SharedViews folder)?
>
> What is necessary to do to support MsTest under SpecsFor? If you are
> removing support for MsTest from SpecsFor.Mvc are there any chances that
> adding support to SpecsFor will succeed? I assume there must have been
> problems for you to be considering dropping support?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MattHoneycutt/SpecsFor/issues/86#issuecomment-186082344>
> .
>
-- 
*Matt Honeycutt*
*Pluralsight Author & Senior Web Application Architect*
[image: Heroic Applications] <http://heroicapplications.com/>
pluralsight vids <http://www.pluralsight.com/author/matt-honeycutt> | blog
<http://trycatchfail.com/> | website <http://heroicapplications.com/> |
@matthoneycutt <http://twitter.com/matthoneycutt>

**Comment by RedX2501** [comment]
So if i wish to use SpecsFor i practically have to use NUnit? From your last comment i gather that even xUnit is unsupported? 

What does it take to add support to a new testing framework? 

I still don't grasp what SpecsFor.Mvc does that SpecsFor does not.  Is it the Iis setup?

**Comment by MattHoneycutt** [comment]
SpecsFor is for unit and integration testing: http://specsfor.com/

SpecsFor.Mvc is for full end-to-end testing through your application's UI: http://specsfor.com/SpecsForMvc/default.cshtml

You can write unit and integration tests against an ASP.NET MVC application *without* SpecsFor.Mvc.  You only need SpecsFor.Mvc if you plan to do full end-to-end testing using UI automation.  You'll want to get a firm understanding of Selenium (http://www.seleniumhq.org/projects/webdriver/) before you even think about starting down that road. 

SpecsFor does require NUnit.  It is a layer on top of NUnit, so you cannot use SpecsFor without NUnit.

Until you've mastered the basics of testing, you should steer clear of using SpecsFor.Mvc.  End-to-end testing is not trivial, and you will need a solid unit and integration testing foundation before you attempt it.  

As I mentioned in the other issue, I think you should start by walking through the Getting Started documentation: https://specsfor.readme.io/docs/getting-started
