### ISSUE TITLE
TestExplorer does not show SpecsFor<MvcWebApp> tests

### ISSUE THREAD

**Issue by RedX2501** [MattHoneycutt/SpecsFor#87]
I'm trying to go for NUnit as it seems that SpecsFor was designed for that.

Unfortunately with Nunit 3.0.1 and NUnit3 Test Adapter all tests for SpecsFor<MvcWebApp> don't show up in the TestExplorer. Tests that don't rely on MvcWebApp show up fine in TestExplorer.

**Comment by RedX2501** [comment]
After investigating some more it seems that the whole test is not found with nunit3.

Nunit3-console does not run the tests not found in Test Explorer.

**Comment by RedX2501** [comment]
Ok so this seems to caused by Nunit not supporting nunit3 but when installing via nuget it seems to install the nunit package which is defaulting now to Nunit 3.

**Comment by MattHoneycutt** [comment]
You'll need to install NUnit 2.x.  SpecsFor does not support NUnit 3 yet.  If you install SpecsFor first, it will install NUnit 2.6.3, the version that SpecsFor was built against.  This version will work with the NUnit 2 VS test adapter, ReSharper, TeamCity, and most other test runners. 

It sounds like you are trying to jump in the deep end without having mastered the basics.  You should start with the tutorial here: https://specsfor.readme.io/docs/getting-started

**Comment by abdelrady** [comment]
@MattHoneycutt Any plans to support nunit 3 soon ?

**Comment by MattHoneycutt** [comment]
It's planned, but I have no ETA on when it'll happen.  Pull requests accepted though. :)

**Comment by be4i** [comment]
Can you please reflect the dependency requirement in nuget, because right now it says "NUnit (>= 2.6.3)" and nuget is allowing me to update the version of NUnit

**Comment by nik0lias** [comment]
I agree with be4i, this would be handy as myself and I suspect many others could have NUnit 3 installed and then work backward to SpecsFor.  It took me quite a bit of googling to find the issue.

Great tool, I may do a pull request time permitting :)

**Comment by MattHoneycutt** [comment]
I've opened #100 to address this, one way or another.
