### ISSUE TITLE
Can't run SpecsFor VS 2015

### ISSUE THREAD

**Issue by larshg** [MattHoneycutt/SpecsFor#89]
When I try to use SpecsFor in [Bonobo](https://github.com/jakubgarfield/Bonobo-Git-Server) it crashes due to the hardcoded path [here](https://github.com/MattHoneycutt/SpecsFor/blob/master/SpecsFor.Mvc/SpecsForMvcConfig.cs#L29)

Is there any way to change what MSBuild tools it has to use?

**Comment by MattHoneycutt** [comment]
This is definitely a bug.  There is a way to change the MSBuild path, but it looks like the validation doesn't respect that.  I'll try to get this fixed ASAP.

**Comment by MattHoneycutt** [comment]
This is fixed in 4.7.2.  Thanks for reporting the issue!
