### ISSUE TITLE
Execute IIS Automatically in Specs MVC

### ISSUE THREAD

**Issue by jt4000** [MattHoneycutt/SpecsFor#93]
What is the source code to execute the IIS express automatically in specs mvc?

**Comment by MattHoneycutt** [comment]
If you are using SpecsFor.Mvc, it will happen automatically as long as you call the UseIISExpress method.  Here's a sample that shows you how to do it: https://github.com/MattHoneycutt/SpecsFor/blob/master/SpecsFor.Mvc.Demo.AcceptanceTests/AssemblyStartup.cs
