### ISSUE TITLE
Creating a Vanilla Test

### ISSUE THREAD

**Issue by rswetnam** [MattHoneycutt/SpecsFor#96]
1. Created new Solution with Web MVC project - taking Microsoft Defaults
2. Created new class library - added Microsoft.Web.MVC and SpecsFor via Nuget
3. Referenced Web Project
4. Created test:
`  public class _when_viewing_index_action : SpecsFor<HomeController>
        {
            private ActionResult _result;

            protected override void When()
            {
                _result = SUT.Index();
            }

            [Test]
            public void then_it_returns_a_view_result()
            {
                _result.ShouldBeType<ViewResult>();
            }
        }`

Ran test:  Message:  Unit Test Runner failed to run tests - System.TypeLoadException: Could not load type 'SpecsFor.SpecsFor '1' from assembly 'Specsfor, Version 1.0.0.0, Culture=neutral, Public Key=null

Posted project on Github at https://github.com/rswetnam/SpecsForTest

**Comment by MattHoneycutt** [comment]
The problem is that you named your spec project "SpecsFor."  It generates a DLL named "SpecsFor.dll," which of course conflicts with SpecsFor's "SpecsFor.dll."  You'll need to pick a more creative spec project name. :)

**Comment by rswetnam** [comment]
I guess they will need to reexamine the expression that it's hard to build something idiot-proof because idiots are so creative... sigh - thanks Matt.

**Comment by MattHoneycutt** [comment]
No problem!  I'm just glad this issue was easy to explain. :)
