### ISSUE TITLE
I have to issues

### ISSUE THREAD

**Issue by RoyGI** [MattHoneycutt/SpecsFor#98]
1) I cannot use specs for with NUNIT 3.0
2) Specs for use protected the given and When, but the then, needs to be public, it cause that i have a Style cop conflict.

Can you change that?

**Comment by MattHoneycutt** [comment]
NUnit 3.0 support is in the works, but I have no ETA on it.

As for StyleCop, what is it complaining about?  That the When and Given are
protected, or that the Then's are public?

On Wed, Jun 8, 2016 at 12:25 PM Roy Gonzalez <notifications@github.com>
wrote:

> 1) I cannot use specs for with NUNIT 3.0
> 2) Specs for use protected the given and When, but the then, needs to be
> public, it cause that i have a Style cop conflict.
>
> Can you change that?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/MattHoneycutt/SpecsFor/issues/98>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAJkzqv69wI7VTlIQzxMLk0SKXGtbvhPks5qJvr_gaJpZM4IxM_9>
> .
>
-- 
*Matt Honeycutt*
*Pluralsight Author & Senior Web Application Architect*
[image: Heroic Applications] <http://heroicapplications.com/>
pluralsight vids <http://www.pluralsight.com/author/matt-honeycutt> | blog
<http://trycatchfail.com/> | website <http://heroicapplications.com/> |
@matthoneycutt <http://twitter.com/matthoneycutt>

**Comment by RoyGI** [comment]
Attaching the issue

**Comment by MattHoneycutt** [comment]
I'm not seeing anything attached here...

**Comment by RoyGI** [comment]
![stylecop](https://cloud.githubusercontent.com/assets/5553128/15905369/e3f6b4d0-2d71-11e6-8384-cbf621407db7.png)

**Comment by MattHoneycutt** [comment]
Oh, I see.  Making When and Given publish would be a major breaking change for SpecsFor, so I'm not going to do that to work around this issue.  On your end though, you can simply put the When and Given at the bottom of your class declaration, below your Then methods.  C# doesn't care what order you declare methods in...
